name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use node v10.15.3
      uses: actions/setup-node@v1
      with:
        node-version: 10.15.3
    - name: Install dependencies
      run: npm install
    - name: Build
      run: npm run build --prod
    - name: Test
      run: npm test 
    - name: E2E
      run: npm run e2e 
